plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.example'
version = '1.0.1'

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/RAGHUVEERSINGH0001/HelloService")

            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}